ADRC_X_r: 2
ADRC_X_h: 0.01
ADRC_X_N: 15
ADRC_X_beta_omega: 300
ADRC_X_b0: 200
ADRC_X_k_d: 0.002
ADRC_X_k_p: 1.6
ADRC_Y_r: 2
ADRC_Y_h: 0.01
ADRC_Y_N: 15
ADRC_Y_beta_omega: 300
ADRC_Y_b0: 200
ADRC_Y_k_d: 0.002
ADRC_Y_k_p: 1.6
ADRC_Z_r: 2
ADRC_Z_h: 0.01
ADRC_Z_N: 15
ADRC_Z_beta_omega: 300
ADRC_Z_b0: 200
ADRC_Z_k_d: 0.002
ADRC_Z_k_p: 1.6
