ADRC_A.r: 300000
ADRC_A.h: 0.005
ADRC_A.N: 2
ADRC_A.beta_01: 100
ADRC_A.beta_02: 1000
ADRC_A.beta_03: 2000
ADRC_A.b0: 0.001
ADRC_A.k_0: 0.002
ADRC_A.k_1: 1.0
ADRC_A.k_2: 0.0005
ADRC_A.N1: 5
ADRC_A.C: 5
ADRC_A.alpha1: 0.8
ADRC_A.alpha2: 1.5
ADRC_A.zeta: 50